id: Detonate URL - WildFire v2.1
version: -1
name: Detonate URL - WildFire v2.1
fromversion: 4.0.0
description: |-
  The webpage detonation is only supported in US cloud.
  Detonate a webpage or a remote file using the WildFire integration. This playbook returns relevant reports to the War Room and file reputations to the context data.
  The detonation supports the following file types -
  APK, JAR, DOC, DOCX, RTF, OOXLS, XLSX, PPT, PPTX, XML, PE32, PDF, DMG, PKG, RAR, 7Z
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ed450ae1-31c5-4fb7-85fb-4c0a4ebda5f0
    type: start
    task:
      id: ed450ae1-31c5-4fb7-85fb-4c0a4ebda5f0
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 98375c12-21d9-4878-8f08-fe923af00cbe
    type: regular
    task:
      id: 98375c12-21d9-4878-8f08-fe923af00cbe
      version: -1
      name: WildFire Upload File URL
      description: Uploads the URL to WildFire for analysis.
      script: WildFire-v2|||wildfire-upload-url
      type: regular
      iscommand: true
      brand: WildFire-v2
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      upload:
        complex:
          root: inputs.URL
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: e52ca0cf-61fc-4de8-8110-c5f511bf01a0
    type: playbook
    task:
      id: e52ca0cf-61fc-4de8-8110-c5f511bf01a0
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        complex:
          root: WildFire
          accessor: Report.URL
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: url
      PollingCommandName:
        simple: wildfire-report
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: WildFire.Report(val.Status != 'Success').URL
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 3844dbd8-2537-4eed-8bce-9888ddf13680
    type: title
    task:
      id: 3844dbd8-2537-4eed-8bce-9888ddf13680
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: e722c7cd-dd01-4b28-89f3-03390b4b76ef
    type: condition
    task:
      id: e722c7cd-dd01-4b28-89f3-03390b4b76ef
      version: -1
      name: Is there a URL to detonate?
      description: Look for file URLs to detonate
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.URL
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 96621185-2ca6-4eb4-8e5a-2b7d0fc37c43
    type: condition
    task:
      id: 96621185-2ca6-4eb4-8e5a-2b7d0fc37c43
      version: -1
      name: Is WildFire-v2 enabled?
      description: Check if integration instance is enabled
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: WildFire-v2
                transformers:
                - operator: getField
                  args:
                    field:
                      value:
                        simple: state
            iscontext: true
          right:
            value:
              simple: active
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 0127711b-2c15-474b-8709-dadb1d0a1c13
    type: regular
    task:
      id: 0127711b-2c15-474b-8709-dadb1d0a1c13
      version: -1
      name: WildFire Get Report
      description: Retrieves results for a file hash using WildFire.
      script: WildFire-v2|||wildfire-report
      type: regular
      iscommand: true
      brand: WildFire-v2
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      format: {}
      hash: {}
      md5: {}
      sha256: {}
      url:
        complex:
          root: WildFire
          accessor: Report.URL
      verbose: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: ca41fd6c-7784-4531-8e70-98c7655f46aa
    type: regular
    task:
      id: ca41fd6c-7784-4531-8e70-98c7655f46aa
      version: -1
      name: WildFire Upload URL
      description: Uploads a URL of a webpage to WildFire for analysis.
      script: WildFire-v2|||wildfire-upload-url
      type: regular
      iscommand: true
      brand: WildFire-v2
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      upload:
        complex:
          root: inputs.URL
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 725,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 411411b1-690c-45cb-8243-fd223288a13b
    type: condition
    task:
      id: 411411b1-690c-45cb-8243-fd223288a13b
      version: -1
      name: Was file url submission successful?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: WildFire
                accessor: Report.Size
            iscontext: true
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 034d46c4-00aa-489e-8cdc-4a91d78bcd07
    type: condition
    task:
      id: 034d46c4-00aa-489e-8cdc-4a91d78bcd07
      version: -1
      name: Was upload finished successfully?
      description: ""
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: WildFire
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: WildFire.Report.Status
                      iscontext: true
                    right:
                      value:
                        simple: Pending
                accessor: Report.URL
            iscontext: true
    view: |-
      {
        "position": {
          "x": 725,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 1055,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: URL
  value:
    complex:
      root: URL
      accessor: Data
  required: false
  description: URL of the webpage or file url to detonate. The URL is taken from the
    context.
  playbookInputQuery: null
- key: Interval
  value:
    simple: "1"
  required: false
  description: Duration for executing the pooling (in minutes)
  playbookInputQuery: null
- key: Timeout
  value:
    simple: "60"
  required: false
  description: The duration after which to stop pooling and to resume the playbook
    (in minutes)
  playbookInputQuery: null
- key: ReportFileType
  value: {}
  required: false
  description: The resource type to download. Default is pdf. xml is also possible.
  playbookInputQuery: null
outputs:
- contextPath: DBotScore
  description: The DBotScore object
  type: unknown
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: File.Size
  description: File size
  type: number
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File.Type
  description: File type e.g. "PE"
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.EntryID
  description: The Entry ID of the sample
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.Name
  description: Filename
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason for the vendor to make the decision
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: IP.Address
  description: IP's relevant to the sample
  type: string
- contextPath: File
  description: The File object
  type: unknown
- contextPath: InfoFile
  description: The report file object
  type: unknown
- contextPath: InfoFile.EntryID
  description: The EntryID of the report file
  type: string
- contextPath: InfoFile.Extension
  description: The extension of the report file
  type: string
- contextPath: InfoFile.Name
  description: The name of the report file
  type: string
- contextPath: InfoFile.Info
  description: The info of the report file
  type: string
- contextPath: InfoFile.Size
  description: The size of the report file
  type: number
- contextPath: InfoFile.Type
  description: The type of the report file
  type: string
- contextPath: File.Malicious
  description: The malicious object
  type: unknown
- contextPath: WildFire.Report
  description: The submission object
  type: unknown
- contextPath: WildFire.Report.MD5
  description: MD5 of the submission
  type: string
- contextPath: WildFire.Report.SHA256
  description: SHA256 of the submission
  type: string
- contextPath: WildFire.Report.FileType
  description: The type of the submission
  type: string
- contextPath: WildFire.Report.Status
  description: The status of the submission
  type: string
- contextPath: WildFire.Report.Size
  description: The size of the submission
  type: number
tests:
- Detonate URL - WildFire v2.1 - Test