id: ReadFile Test
version: -1
name: ReadFile Test
description: Creates a text file and tests ReadFile script
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 586a5318-debb-45a7-82a8-c1985ab18b62
    type: start
    task:
      id: 586a5318-debb-45a7-82a8-c1985ab18b62
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: e63e3873-1f29-47eb-862c-545aa25ed903
    type: regular
    task:
      id: e63e3873-1f29-47eb-862c-545aa25ed903
      version: -1
      name: Create text file
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      data:
        simple: TEST
      entryId: {}
      filename:
        simple: test.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "2":
    id: "2"
    taskid: 49891d6b-9512-49ff-83ca-3abe2eb2fc0c
    type: regular
    task:
      id: 49891d6b-9512-49ff-83ca-3abe2eb2fc0c
      version: -1
      name: Delete context (all)
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    id: "3"
    taskid: 3b15d5c4-1046-44fe-8b58-8bab8fe22151
    type: regular
    task:
      id: 3b15d5c4-1046-44fe-8b58-8bab8fe22151
      version: -1
      name: ReadFile
      scriptName: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    id: "4"
    taskid: 3a34d28e-b963-4c3f-8862-fa77fcabe646
    type: regular
    task:
      id: 3a34d28e-b963-4c3f-8862-fa77fcabe646
      version: -1
      name: Verify Context
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      expectedValue:
        simple: TEST
      fields: {}
      path:
        simple: FileData
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    id: "5"
    taskid: c81321cb-be51-4541-8cf9-43c04d093552
    type: title
    task:
      id: c81321cb-be51-4541-8cf9-43c04d093552
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
